apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: smu6dlcvc-nodejs 
  janus-idp.io/tekton: smu6dlcvc-nodejs
  backstage.io/kubernetes-id: smu6dlcvc-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: smu6dlcvc-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  